;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	consult-buffer
	evil-append
	evil-force-normal-state
	evil-insert
	evil-next-line
	evil-normal-state
	evil-undo
	))

(setq mc/cmds-to-run-once
      '(
	ace-jump-done
	ace-jump-move
	ace-mc-add-char
	ace-mc-add-multiple-cursors
	ace-mc-add-single-cursor
	ace-mc-do-keyboard-reset
	ace-mc-quick-exchange
	evil-mouse-drag-region
	evil-previous-line
	evil-visual-line
	hungry-delete-backward
	))
